; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM14
board_build.partitions = min_spiffs.csv
data_dir = src/data
monitor_port = COM14
; Local Arduino libraries provide: ui (SquareLine), TFT_eSPI (with custom User_Setup.h),
; Adafruit_NeoPixel, Adafruit_PWM_Servo_Driver_Library, Adafruit_BusIO, ArduinoJson
lib_extra_dirs = ../libraries
lib_deps =
    lvgl/lvgl@^8.3.0
    paulstoffregen/XPT2046_Touchscreen
    me-no-dev/AsyncTCP
    me-no-dev/ESPAsyncWebServer
    ayushsharma82/ElegantOTA@^2.2.9
    dfrobot/DFRobotDFPlayerMini
    witnessmenow/UniversalTelegramBot
    bblanchon/ArduinoJson
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I../libraries
